# Generated by Django 3.1.5 on 2021-02-11 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='month',
        ),
        migrations.AddField(
            model_name='recipe',
            name='month',
            field=models.ManyToManyField(to='recipes.Month'),
        ),
    ]
