# Generated by Django 3.1.5 on 2021-02-26 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='batch_cook',
            field=models.CharField(default='null', max_length=254),
            preserve_default=False,
        ),
    ]
