# Generated by Django 3.1.5 on 2021-02-18 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='recipe',
            new_name='name',
        ),
    ]
