# Generated by Django 3.1.5 on 2021-02-18 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0002_auto_20210218_1634'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='name',
            new_name='recipe',
        ),
    ]
